apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/logging-app*.log
      tag app
      <parse>
        @type json

        time_type string
        time_format %Y-%m-%dT%H:%M:%S.%L%z
        keep_time_key true
      </parse>
    </source>

    <match app>
      @type stdout
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logging-app
  template:
    metadata:
      labels:
        app: logging-app
    spec:
      containers:
        - name: logging-app
          image: logging
          imagePullPolicy: Never
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: logger
          image: logger
          imagePullPolicy: Never
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 24224
          volumeMounts:
            - mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
              name: logging-config
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
      volumes:
        - name: logging-config
          configMap:
            name: logging-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
