version: "3"

services:
  logging:
    image: logging
    ports:
      - 3000:3000
    volumes:
      - ./test.log:/app/test.log
  fluent:
    depends_on:
      - db
    image: logger
    volumes:
      - ./test.log:/test.log
      - ./fluent.conf:/fluentd/etc/fluent.conf
  db:
    image: mongo
