version: "3"

services:
  logging:
    image: logging
    ports:
      - 3000:3000
    volumes:
      - ./test.log:/app/test.log
  fluent:
    depends_on:
      - elasticsearch
    image: logger
    volumes:
      - ./test.log:/test.log
      - ./fluent.conf:/fluentd/etc/fluent.conf
  elasticsearch:
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
  kibana:
    depends_on:
      - elasticsearch
    image: kibana:7.10.1
    ports:
      - 5601:5601
