version: "3"

services:
  logging:
    build: .
    volumes:
      - ./logs:/app/logs
    ports:
      - 3000:3000
  fluent:
    depends_on:
      - elasticsearch
    build:
      context: .
      dockerfile: Dockerfile.fluent
    volumes:
      - ./logs:/logs
      - ./fluent.conf:/fluentd/etc/fluent.conf
  elasticsearch:
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
  kibana:
    depends_on:
      - elasticsearch
    image: kibana:7.10.1
    ports:
      - 5601:5601
